; Listing generated by Microsoft (R) Optimizing Compiler Version 19.30.30709.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__5B95AFCC_concurrencysal@h DB 01H
__AF7C3541_sal@h DB 01H
__FF4CBCD4_vadefs@h DB 01H
__EF9B48C8_vcruntime@h DB 01H
__0B460DD5_xkeycheck@h DB 01H
__518BDD87_yvals_core@h DB 01H
__3937FC8D_limits@h DB 01H
__A64D14EB_climits DB 01H
__6569C2CA_corecrt@h DB 01H
__356604CF_vcruntime_new@h DB 01H
__6C55A9F6_vcruntime_new_debug@h DB 01H
__49916C16_crtdbg@h DB 01H
__98E9459B_crtdefs@h DB 01H
__7B851503_use_ansi@h DB 01H
__94E280A6_yvals@h DB 01H
__741AE07E_corecrt_math@h DB 01H
__91D68F2D_math@h DB 01H
__6C20D4D3_corecrt_malloc@h DB 01H
__C9393812_stddef@h DB 01H
__D493B9BD_corecrt_search@h DB 01H
__1473E23E_corecrt_wstdlib@h DB 01H
__B49664B7_stdlib@h DB 01H
__22A23619_cstdlib DB 01H
__808B274A_xtr1common DB 01H
__DB8DB16E_intrin0@inl@h DB 01H
__81C4FC90_intrin0@h DB 01H
__CDC63BF6_cmath DB 01H
__A2143F22_corecrt_stdio_config@h DB 01H
__829E1958_corecrt_wstdio@h DB 01H
__6DFAE8B8_stdio@h DB 01H
__3434F1A4_cstdio DB 01H
__CDDAF8CA_errno@h DB 01H
__E6DA1474_vcruntime_string@h DB 01H
__1FEB9909_corecrt_memcpy_s@h DB 01H
__A751F051_corecrt_memory@h DB 01H
__9200769A_corecrt_wstring@h DB 01H
__32E5F013_string@h DB 01H
__6E309EF9_cstring DB 01H
__C6E16F6F_corecrt_wconio@h DB 01H
__5DB64B66_corecrt_wctype@h DB 01H
__CB8D9B53_corecrt_wdirect@h DB 01H
__A9063C41_corecrt_share@h DB 01H
__6D390390_corecrt_wio@h DB 01H
__61BDDCD5_corecrt_wprocess@h DB 01H
__1157D6BA_corecrt_wtime@h DB 01H
__64F617E8_types@h DB 01H
__1DC1E279_stat@h DB 01H
__93DC0B45_wchar@h DB 01H
__AEBF27F7_cwchar DB 01H
__8769ECB4_cstddef DB 01H
__4153D9FF_initializer_list DB 01H
__E2B02480_xstddef DB 01H
__ED7FA2C1_iosfwd DB 01H
__8741D2B2_stdint@h DB 01H
__9FFCD764_cstdint DB 01H
__45EFCB1E_type_traits DB 01H
__15AFB392_utility DB 01H
__EB99AA4F_xutility DB 01H
__FA351D0F_iterator DB 01H
__5B81F060_share@h DB 01H
__69F41CE0___msvc_system_error_abi@hpp DB 01H
__A915855F_cerrno DB 01H
__20BB4341_malloc@h DB 01H
__3C5D8049_corecrt_terminate@h DB 01H
__517DF72F_eh@h DB 01H
__64BBACA4_vcruntime_exception@h DB 01H
__50B62B0D_exception DB 01H
__158E8E48_float@h DB 01H
__47703A23_cfloat DB 01H
__35511E07_isa_availability@h DB 01H
__21967747_limits DB 01H
__08BB6DA5_new DB 01H
__5ABAA7DB_xatomic@h DB 01H
__7F3AD051_xmemory DB 01H
__0BE956CD_xstring DB 01H
__D9F81150_stdexcept DB 01H
__121303D7_xcall_once@h DB 01H
__3C7795A9_xerrc@h DB 01H
__A0B61CF9_time@h DB 01H
__0B75A7FE_ctime DB 01H
__5D5D490E_xtimec@h DB 01H
__1ACB22B0_xthreads@h DB 01H
__4AA32B85_atomic DB 01H
__AD4E11F7_system_error DB 01H
__C40BCBAA_vcruntime_typeinfo@h DB 01H
__9B465956_typeinfo DB 01H
__9D387BC9_memory DB 01H
__B17D2CC6_xfacet DB 01H
__7C272235___msvc_xlocinfo_types@hpp DB 01H
__B2D2BA86_ctype@h DB 01H
__3BFF1603_cctype DB 01H
__A3D09DBA_locale@h DB 01H
__B10EEAC8_clocale DB 01H
__84CFBA9E_xlocinfo DB 01H
__D4D722FC_xlocale DB 01H
__BD2ACD8D_xiosbase DB 01H
__DB58A9EC_streambuf DB 01H
__4A5044EB_xlocnum DB 01H
__F07657B3_ios DB 01H
__C7C7F838_ostream DB 01H
__A417CD02_istream DB 01H
__89E0D050_iostream DB 01H
__18442382_Math@h DB 01H
__53ED2458_ConsoleApplication1@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?__empty_global_delete@@YAXPEAX@Z		; __empty_global_delete
PUBLIC	?__empty_global_delete@@YAXPEAX_K@Z		; __empty_global_delete
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0O@NFOCKKMG@Hello?5World?$CB?6@		; `string'
EXTRN	__imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ:PROC
EXTRN	?Log@@YAXH@Z:PROC				; Log
EXTRN	?Log@@YAXPEBD@Z:PROC				; Log
EXTRN	__CheckForDebuggerJustMyCode:PROC
EXTRN	__imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A:BYTE
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX@Z DD imagerel $LN3
	DD	imagerel $LN3+33
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?__empty_global_delete@@YAXPEAX_K@Z DD imagerel $LN3
	DD	imagerel $LN3+38
	DD	imagerel $unwind$?__empty_global_delete@@YAXPEAX_K@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Multiply@@YAHHH@Z DD imagerel ?Multiply@@YAHHH@Z
	DD	imagerel ?Multiply@@YAHHH@Z+43
	DD	imagerel $unwind$?Multiply@@YAHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN3
	DD	imagerel $LN3+92
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0O@NFOCKKMG@Hello?5World?$CB?6@
CONST	SEGMENT
??_C@_0O@NFOCKKMG@Hello?5World?$CB?6@ DB 'Hello World!', 0aH, 00H ; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	025030b01H
	DD	0d206230bH
	DD	05002H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Multiply@@YAHHH@Z DD 025031201H
	DD	0b20d2312H
	DD	05009H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX_K@Z DD 025031401H
	DD	0b20f2314H
	DD	0500bH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?__empty_global_delete@@YAXPEAX@Z DD 025030f01H
	DD	0b20a230fH
	DD	05006H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT main
_TEXT	SEGMENT
var$ = 0
main	PROC						; COMDAT
; File C:\Users\jakeh\Documents\GitHub\CppLearning\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp
; Line 12
$LN3:
	push	rbp
	sub	rsp, 112				; 00000070H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__53ED2458_ConsoleApplication1@cpp
	call	__CheckForDebuggerJustMyCode
; Line 13
	mov	BYTE PTR var$[rbp], 0
; Line 15
	mov	edx, 5
	mov	ecx, 5
	call	?Multiply@@YAHHH@Z			; Multiply
	mov	ecx, eax
	call	?Log@@YAXH@Z				; Log
; Line 16
	lea	rcx, OFFSET FLAT:??_C@_0O@NFOCKKMG@Hello?5World?$CB?6@
	call	?Log@@YAXPEBD@Z				; Log
; Line 17
	mov	ecx, 4
	call	?Log@@YAXH@Z				; Log
; Line 18
	mov	rcx, QWORD PTR __imp_?cin@std@@3V?$basic_istream@DU?$char_traits@D@std@@@1@A
	call	QWORD PTR __imp_?get@?$basic_istream@DU?$char_traits@D@std@@@std@@QEAAHXZ
; Line 19
	xor	eax, eax
	lea	rsp, QWORD PTR [rbp+80]
	pop	rbp
	ret	0
main	ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?Multiply@@YAHHH@Z
_TEXT	SEGMENT
a$ = 80
b$ = 88
?Multiply@@YAHHH@Z PROC					; Multiply, COMDAT
; File C:\Users\jakeh\Documents\GitHub\CppLearning\ConsoleApplication1\ConsoleApplication1\Math.h
; Line 2
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__18442382_Math@h
	call	__CheckForDebuggerJustMyCode
; Line 3
	mov	eax, DWORD PTR a$[rbp]
	imul	eax, DWORD PTR b$[rbp]
; Line 4
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?Multiply@@YAHHH@Z ENDP					; Multiply
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX_K@Z
_TEXT	SEGMENT
__formal$ = 80
__formal$ = 88
?__empty_global_delete@@YAXPEAX_K@Z PROC		; __empty_global_delete, COMDAT
; File C:\Users\jakeh\Documents\GitHub\CppLearning\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp
; Line 31
$LN3:
	mov	QWORD PTR [rsp+16], rdx
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__53ED2458_ConsoleApplication1@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX_K@Z ENDP		; __empty_global_delete
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?__empty_global_delete@@YAXPEAX@Z
_TEXT	SEGMENT
__formal$ = 80
?__empty_global_delete@@YAXPEAX@Z PROC			; __empty_global_delete, COMDAT
; File C:\Users\jakeh\Documents\GitHub\CppLearning\ConsoleApplication1\ConsoleApplication1\ConsoleApplication1.cpp
; Line 31
$LN3:
	mov	QWORD PTR [rsp+8], rcx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__53ED2458_ConsoleApplication1@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?__empty_global_delete@@YAXPEAX@Z ENDP			; __empty_global_delete
_TEXT	ENDS
END
