; Listing generated by Microsoft (R) Optimizing Compiler Version 19.30.30709.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__18442382_Math@h DB 01H
__D8BD74D4_Math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?initMultiply@@YAHHH@Z				; initMultiply
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?Multiply@@YAHHH@Z DD imagerel ?Multiply@@YAHHH@Z
	DD	imagerel ?Multiply@@YAHHH@Z+43
	DD	imagerel $unwind$?Multiply@@YAHHH@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?initMultiply@@YAHHH@Z DD imagerel $LN3
	DD	imagerel $LN3+47
	DD	imagerel $unwind$?initMultiply@@YAHHH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?initMultiply@@YAHHH@Z DD 025031201H
	DD	0b20d2312H
	DD	05009H
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?Multiply@@YAHHH@Z DD 025031201H
	DD	0b20d2312H
	DD	05009H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?initMultiply@@YAHHH@Z
_TEXT	SEGMENT
input1$ = 80
input2$ = 88
?initMultiply@@YAHHH@Z PROC				; initMultiply, COMDAT
; File C:\Users\jakeh\Documents\GitHub\CppLearning\ConsoleApplication1\ConsoleApplication1\Math.cpp
; Line 7
$LN3:
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__D8BD74D4_Math@cpp
	call	__CheckForDebuggerJustMyCode
; Line 8
	mov	edx, DWORD PTR input2$[rbp]
	mov	ecx, DWORD PTR input1$[rbp]
	call	?Multiply@@YAHHH@Z			; Multiply
; Line 9
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?initMultiply@@YAHHH@Z ENDP				; initMultiply
_TEXT	ENDS
; Function compile flags: /Odtp /ZI
;	COMDAT ?Multiply@@YAHHH@Z
_TEXT	SEGMENT
a$ = 80
b$ = 88
?Multiply@@YAHHH@Z PROC					; Multiply, COMDAT
; File C:\Users\jakeh\Documents\GitHub\CppLearning\ConsoleApplication1\ConsoleApplication1\Math.h
; Line 2
	mov	DWORD PTR [rsp+16], edx
	mov	DWORD PTR [rsp+8], ecx
	push	rbp
	sub	rsp, 96					; 00000060H
	lea	rbp, QWORD PTR [rsp+32]
	lea	rcx, OFFSET FLAT:__18442382_Math@h
	call	__CheckForDebuggerJustMyCode
; Line 3
	mov	eax, DWORD PTR a$[rbp]
	imul	eax, DWORD PTR b$[rbp]
; Line 4
	lea	rsp, QWORD PTR [rbp+64]
	pop	rbp
	ret	0
?Multiply@@YAHHH@Z ENDP					; Multiply
_TEXT	ENDS
END
